package com.rideflux.protocol.familyscooter.xiaomi

import java.security.interfaces.ECPublicKey
import org.junit.Assert.*
import org.junit.Test

/** Fixed results independently generated by tools/mi_crypto_vectors.py (cryptography AESCCM/HKDF). */
class MiCryptoTest {
    private fun hex(value: String) = value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
    private fun keys() = MiKeys.login(ByteArray(12) { it.toByte() }, ByteArray(16) { it.toByte() },
        ByteArray(16) { (it + 16).toByte() })

    @Test fun setupMatchesIndependentVectorAndWipes() {
        val setup = MiKeys.setup(ByteArray(32) { it.toByte() })
        assertArrayEquals(hex("83d3ce31ee8ca124d82039c3"), setup.token)
        assertArrayEquals(hex("92cfd4e1f0507572fa38504ec3cd71d3"), setup.didKey)
        val encrypted = MiCcm.encrypt(setup.didKey, ByteArray(12) { (it + 16).toByte() },
            "test-device-id".toByteArray(), "devID".toByteArray())
        assertArrayEquals(hex("22e93b37c78e591924fc3a53ce80b7a11754"), encrypted)
        assertEquals("MiSetupKeys(<redacted>)", setup.toString())
        setup.wipe()
        assertTrue(setup.token.all { it == 0.toByte() } && setup.didKey.all { it == 0.toByte() })
    }

    @Test fun loginMatchesIndependentDerivationAndProofVectors() {
        val keys = keys()
        assertArrayEquals(hex("18eea5008b0cee3744c215c7cd9ead26"), keys.devKey)
        assertArrayEquals(hex("8670b5056f4a71ffd1d4ea419e3c84be"), keys.appKey)
        assertArrayEquals(hex("2a03093f"), keys.devIv)
        assertArrayEquals(hex("8eb73a36"), keys.appIv)
        assertArrayEquals(hex("6ead8b835115a14a79957476c5fac6e2956a896ee23955b35218efd40d684631"), keys.loginInfo)
        assertArrayEquals(hex("99936f1c9a0a1dcda373d014172ccbf46564268d2b56c02f0ef3ec6ead544333"), keys.scooterProof)
        assertEquals("MiLoginKeys(<redacted>)", keys.toString())
        keys.wipe()
        listOf(keys.devKey, keys.appKey, keys.devIv, keys.appIv, keys.loginInfo, keys.scooterProof)
            .forEach { assertTrue(it.all { byte -> byte == 0.toByte() }) }
    }

    @Test fun hkdfMatchesRfc5869CaseOne() {
        val result = MiHkdf.derive(ByteArray(22) { 0x0b }, hex("000102030405060708090a0b0c"),
            hex("f0f1f2f3f4f5f6f7f8f9"), 42)
        assertArrayEquals(hex("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"), result)
        assertEquals(0, MiHkdf.derive(byteArrayOf(), null, byteArrayOf(), 0).size)
        assertArrayEquals(MiHkdf.hmac(ByteArray(32), byteArrayOf(1)), MiHkdf.hmac(byteArrayOf(), byteArrayOf(1)))
        expectIllegal { MiHkdf.derive(byteArrayOf(), null, byteArrayOf(), -1) }
        expectIllegal { MiHkdf.derive(byteArrayOf(), null, byteArrayOf(), 8161) }
    }

    @Test fun ccmHandlesEmptyAndExtendedAadIndependentVectors() {
        assertArrayEquals(hex("be3ce2d4"), MiCcm.encrypt(ByteArray(16), ByteArray(12), byteArrayOf()))
        assertArrayEquals(byteArrayOf(), MiCcm.decrypt(ByteArray(16), ByteArray(12), hex("be3ce2d4")))
        val aad = ByteArray(0xFF00)
        val encrypted = MiCcm.encrypt(ByteArray(16), ByteArray(12), "abc".toByteArray(), aad)
        assertArrayEquals(hex("0fa53c0901f6ac"), encrypted)
        assertArrayEquals("abc".toByteArray(), MiCcm.decrypt(ByteArray(16), ByteArray(12), encrypted, aad))
    }

    @Test fun ccmRfc3610InputAdaptedToMiParametersMatchesPython() {
        // RFC3610 Packet Vector1 inputs with final nonce byte removed and M changed to4.
        // Expected is independently generated by Python, not the RFC's original output.
        val key = ByteArray(16) { (0xC0 + it).toByte() }
        val nonce = hex("00000003020100a0a1a2a3a4")
        val data = ByteArray(23) { (8 + it).toByte() }
        val aad = ByteArray(8) { it.toByte() }
        val expected = hex("3d3cef188df7830d987b22e465f5b67fb14adc630ab5ac4093416f")
        assertArrayEquals(expected, MiCcm.encrypt(key, nonce, data, aad))
        assertArrayEquals(data, MiCcm.decrypt(key, nonce, expected, aad))
    }

    @Test fun ecdhMatchesIndependentFixedPrivateScalars() {
        val parameters = java.security.AlgorithmParameters.getInstance("EC").apply {
            init(java.security.spec.ECGenParameterSpec("secp256r1"))
        }.getParameterSpec(java.security.spec.ECParameterSpec::class.java)
        val private = java.security.KeyFactory.getInstance("EC").generatePrivate(
            java.security.spec.ECPrivateKeySpec(java.math.BigInteger.ONE, parameters))
        // Public point for scalar2; x is also ECDH result when local scalar1.
        val peer = hex("7cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc47669978" +
            "07775510db8ed040293d9ac69f7430dbba7dade63ce982299e04b79d227873d1")
        assertArrayEquals(hex("7cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc47669978"),
            MiEcdh.sharedSecret(private, peer))
    }

    @Test fun ccmRejectsMalformedAndTamperedInputs() {
        expectIllegal { MiCcm.encrypt(ByteArray(15), ByteArray(12), byteArrayOf()) }
        expectIllegal { MiCcm.encrypt(ByteArray(16), ByteArray(11), byteArrayOf()) }
        expectIllegal { MiCcm.decrypt(ByteArray(16), ByteArray(12), ByteArray(3)) }
        val encrypted = MiCcm.encrypt(ByteArray(16), ByteArray(12), byteArrayOf(1, 2))
        encrypted[0] = (encrypted[0].toInt() xor 1).toByte()
        try {
            MiCcm.decrypt(ByteArray(16), ByteArray(12), encrypted)
            fail("Accepted corrupt ciphertext")
        } catch (error: MiCcm.AuthenticationException) {
            assertEquals("CCM authentication failed", error.message)
        }
    }

    @Test fun keyDerivationRejectsInvalidLengths() {
        expectIllegal { MiKeys.setup(ByteArray(31)) }
        expectIllegal { MiKeys.login(ByteArray(11), ByteArray(16), ByteArray(16)) }
        expectIllegal { MiKeys.login(ByteArray(12), ByteArray(15), ByteArray(16)) }
        expectIllegal { MiKeys.login(ByteArray(12), ByteArray(16), ByteArray(15)) }
    }

    @Test fun ecdhInteroperatesAndRejectsInvalidPoints() {
        val a = MiEcdh.generate()
        val b = MiEcdh.generate()
        val aRaw = MiEcdh.publicRaw(a.public as ECPublicKey)
        val bRaw = MiEcdh.publicRaw(b.public as ECPublicKey)
        assertArrayEquals(aRaw, MiEcdh.publicRaw(MiEcdh.decodePublic(aRaw)))
        val ab = MiEcdh.sharedSecret(a.private, bRaw)
        val ba = MiEcdh.sharedSecret(b.private, aRaw)
        assertArrayEquals(ab, ba)
        // Equivalent to the reference Rust randomized calc_did test (no cargo available).
        val derived = MiKeys.setup(ab)
        assertEquals(12, derived.token.size)
        assertEquals(24, MiCcm.encrypt(derived.didKey, ByteArray(12) { (it + 16).toByte() }, ByteArray(20), "devID".toByteArray()).size)
        ab.fill(0); ba.fill(0); derived.wipe()
        expectIllegal { MiEcdh.decodePublic(ByteArray(63)) }
        expectIllegal { MiEcdh.decodePublic(ByteArray(64)) }
        expectIllegal { MiEcdh.decodePublic(ByteArray(64) { 0xFF.toByte() }) }
    }

    @Test fun uartBothDirectionsMatchIndependentVectors() {
        val keys = keys()
        val frame = MiUartFrame(keys, randomBytes = { hex("aabbccdd") })
        assertArrayEquals(hex("55ab0300005856bb9d9ac700e941cc54103bfa"), frame.encrypt(hex("032001b020")))
        assertArrayEquals(hex("042301b50000"), frame.decrypt(hex("55ab0411007d345f18183c0e0bcff13ec2ace9fa")))
        assertEquals("MiUartFrame(<redacted>)", frame.toString())
        keys.wipe() // The session owns copies and survives wiping the auth result.
        assertEquals(1, frame.encrypt(hex("032001b020"))[3].toInt())
        frame.close()
        frame.close()
        expectFrame(MiFrameError.CLOSED) { frame.encrypt(hex("032001b020")) }
        expectFrame(MiFrameError.CLOSED) { frame.decrypt(byteArrayOf()) }
    }

    @Test fun uartCounterPolicyRefusesWrapAndLegacyIsExplicit() {
        val keys = keys()
        val frame = MiUartFrame(keys, randomBytes = { ByteArray(4) })
        val message = hex("022001b0")
        repeat(65536) { number ->
            val encrypted = frame.encrypt(message)
            assertEquals(number, (encrypted[3].toInt() and 255) or ((encrypted[4].toInt() and 255) shl 8))
        }
        expectFrame(MiFrameError.COUNTER_EXHAUSTED) { frame.encrypt(message) }
        frame.close()
        val legacy = MiUartFrame(keys, MiSessionOptions(MiCounterMode.LEGACY_ZERO), { ByteArray(4) })
        assertArrayEquals(legacy.encrypt(message), legacy.encrypt(message))
        legacy.close(); keys.wipe()
    }

    @Test fun uartRejectsMalformedHeaderChecksumAndAuthentication() {
        val keys = keys()
        val frame = MiUartFrame(keys)
        expectFrame(MiFrameError.MALFORMED) { frame.encrypt(byteArrayOf()) }
        expectFrame(MiFrameError.MALFORMED) { frame.encrypt(hex("052001b0")) }
        val invalidRandom = MiUartFrame(keys, randomBytes = { ByteArray(3) })
        expectFrame(MiFrameError.MALFORMED) { invalidRandom.encrypt(hex("022001b0")) }
        invalidRandom.close()
        val valid = hex("55ab0411007d345f18183c0e0bcff13ec2ace9fa")
        for (length in 0 until valid.size) {
            expectFrame(MiFrameError.MALFORMED) { frame.decrypt(valid.copyOf(length)) }
        }
        expectFrame(MiFrameError.HEADER) { frame.decrypt(valid.copyOf().apply { this[0] = 0 }) }
        expectFrame(MiFrameError.MALFORMED) { frame.decrypt(valid.copyOf().apply { this[2] = 1 }) }
        expectFrame(MiFrameError.CHECKSUM) { frame.decrypt(valid.copyOf().apply { this[5] = 0 }) }
        val tampered = valid.copyOf().apply { this[5] = 0 }
        var sum = 0
        for (i in 2 until tampered.size - 2) sum += tampered[i].toInt() and 255
        val checksum = sum.inv() and 65535
        tampered[tampered.size - 2] = checksum.toByte(); tampered[tampered.size - 1] = (checksum ushr 8).toByte()
        expectFrame(MiFrameError.AUTHENTICATION) { frame.decrypt(tampered) }
        frame.close(); keys.wipe()
    }

    @Test fun hostileFramesOnlyProduceDocumentedErrors() {
        val keys = keys()
        val frame = MiUartFrame(keys)
        val random = java.util.Random(1984)
        repeat(1000) {
            val bytes = ByteArray(random.nextInt(300)).also { random.nextBytes(it) }
            try { frame.decrypt(bytes); fail("Random frame accepted") }
            catch (error: MiFrameException) { assertNotNull(error.reason) }
        }
        frame.close(); keys.wipe()
    }

    private fun expectIllegal(block: () -> Unit) {
        try { block(); fail("Expected invalid input") } catch (_: IllegalArgumentException) { }
    }
    private fun expectFrame(reason: MiFrameError, block: () -> Unit) {
        try { block(); fail("Expected frame error") }
        catch (error: MiFrameException) { assertEquals(reason, error.reason) }
    }
}
